services:
  db:
    image: postgres:16
    container_name: newsfeed-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-newsfeed}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-newsfeed}"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - app-networks

  backend:
    image: dkakushkin/academy:latest
    container_name: newsfeed-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=${POSTGRES_DB:-newsfeed};Username=${POSTGRES_USER:-app};Password=${POSTGRES_PASSWORD:-secret}"
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - app-networks

  frontend:
    image: dkakushkin/frontend:latest
    container_name: newsfeed-frontend
    depends_on:
      - backend
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - app-networks

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_etc:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      - backend
    networks:
      - app-networks

  certbot-initial:
    image: certbot/certbot
    container_name: certbot-initial
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot -d kakushkin-dima.ru -d www.kakushkin-dima.ru --non-interactive --agree-tos --email kakushkin-dima@email.com
    depends_on:
      - nginx
    networks:
      - app-networks

  certbot-renew:
      image: certbot/certbot
      container_name: certbot-renew
      volumes:
        - certbot_etc:/etc/letsencrypt
        - certbot_www:/var/www/certbot
      entrypoint: sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h; done"
      depends_on:
        - certbot-initial
      networks:
        - app-networks

volumes:
  db_data:
  certbot_etc:
  certbot_www:

networks:
  app-networks:
    driver: bridge
