events {}

http {
    server {
        listen 80;
        server_name kakushkin-dima.ru www.kakushkin-dima.ru;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name kakushkin-dima.ru www.kakushkin-dima.ru;
 
        ssl_certificate /etc/letsencrypt/live/kakushkin-dima.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/kakushkin-dima.ru/privkey.pem;


        location / {
            proxy_pass http://frontend:80;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://backend:8080;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr; 
        }
    }
}
